name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - [ "master", "main" ] 

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BloodPressureApp

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore BloodPressureApp.sln

      # TODO: Action for checking vulnerable/out-of-date packages

      - name: Build
        run: dotnet build BloodPressureApp.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test BloodPressureApp.sln --configuration Release --no-restore --no-build

      #- name: Publish
      #  run: dotnet publish BloodPressureApp.sln --configuration Release --no-restore --no-build